<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Le meilleur site pour organiser vos voyages à l'étranger!">
  <title>Easy Voyage</title>
  <!-- <link href="../public/css/main.css" rel="stylesheet"> -->
  <?= $env->getPathCss('css/main.css'); ?>
  <script src="https://kit.fontawesome.com/486886617b.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>

<body>
  <header>
    <?php

    if (!isset($_SESSION['role_id'])) {
      require '../controllers/header.php';
    } elseif ($_SESSION['role_id'] == 2) {
      require '../controllers/headerAdmin.php';
    } else {
      require '../controllers/header.php';
    }

    ?>
  </header>
  <div id="message"></div>
  <main>
    <?php if (isset($_SESSION['user_firstname'])) : ?>
      <div class="welcome">
        <p>Bienvenue, <?= htmlspecialchars($_SESSION['user_firstname']) ?> !</p>
      <?php endif; ?>
      </div>
      <?php require '../views/' . $template . '.phtml'; ?>
  </main>
  <?php require '../controllers/footer.php'; ?>

  <!-- <script src="public/js/stick.js"></script> -->
</body>

</html>