<h1 class="form__title titlePage">Créer un voyage</h1>
<form action="" id="createJourney" method="post" class="form__wrapper">
    <!-- ... -->
    <select name="departure_id" id="departure_id"  class="form__select">
        <?php foreach ($departures as $departure) : ?>
            <option value="<?= htmlspecialchars($departure['id']) ?>"><?= htmlspecialchars($departure['departure_label']) ?></option>
        <?php endforeach; ?>
    </select>
    <br>
    <select name="category_id" id="category_id"  class="form__select">
        <?php foreach ($categories as $category) : ?>
            <option value="<?= htmlspecialchars($category['id']) ?>"><?= htmlspecialchars($category['category_label']) ?></option>
        <?php endforeach; ?>
    </select>
    <br>
    <select name="country_id" id="country_id"  class="form__select">
        <?php foreach ($countries as $country) : ?>
            <option value="<?= htmlspecialchars($country['id']) ?>"><?= htmlspecialchars($country['country_label']) ?></option>
        <?php endforeach; ?>
    </select>
    <br>
    <button type="submit" class="form__submit">Créer le voyage</button>
</form>
<script src="public/js/createJourney.js"></script>
