<footer>
  <div class="footer-container">
    <div class="footer-logo-address">
      <a href="home"><img src="public/img/header-footer/small-logo.png" alt="Logo du site" class="footer-logo"></a>

      <p>Adresse postale de l'entreprise<br>
        Rue Example, 12345 Ville<br>
        Pays</p>
    </div>
    <nav class="footer-navigation">
      <ul>
        <li><a href="law">Mentions légales</a></li>
        <li><a href="politics">Politique de confidentialité</a></li>
        <li><a href="team">Qui sommes-nous?</a></li>
      </ul>
    </nav>
    <nav class="footer-social">
      <ul>
        <li><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-facebook"></i></a></li>
        <li><a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-instagram"></i></a></li>
        <li><a href="https://www.youtube.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-youtube"></i></a></li>
        <li><a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-linkedin"></i></a></li>
        <li><a href="https://www.twitter.com/" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-twitter"></i></a></li>
      </ul>
    </nav>
  </div>
</footer>