<h1 class="titlePage">Liste des voyages</h1>
<div class="table-wrapper">
  <table class="journey-table">
    <thead>
      <tr class="journey-table__row">
        <th class="journey-table__header">ID</th>
        <th class="journey-table__header">Nom du séjour</th>
        <th class="journey-table__header">Titre de l'intro</th>
        <!-- <th class="journey-table__header">Description</th>
        <th class="journey-table__header">Durée</th>
        <th class="journey-table__header">Prix</th>
        <th class="journey-table__header">Hôtel</th>
        <th class="journey-table__header">Description</th>
        <th class="journey-table__header">Circuit</th>
        <th class="journey-table__header">Description</th>
        <th class="journey-table__header">Formalités</th> -->
        <th class="journey-table__header">Pays</th>
        <th class="journey-table__header">Periode</th>
        <th class="journey-table__header">Catégorie</th>
        <th class="journey-table__header">Lire</th>
        <th class="journey-table__header">Ajouter une photo</th>

        <th class="journey-table__header">Effacer</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($journeys as $journey) : ?>
        <tr class="journey-table__row">
          <td class="journey-table__cell"><?= htmlspecialchars($journey['id']) ?></td>
          <td class="journey-table__cell"><?= htmlspecialchars($journey['journey_label']) ?></td>
          <td class="journey-table__cell"><?= htmlspecialchars($journey['journey_title']) ?></td>


          <td class="journey-table__cell"><?= htmlspecialchars($journey['country']); ?></td>
          <td class="journey-table__cell"><?= htmlspecialchars($journey['departure']); ?></td>
          <td class="journey-table__cell"><?= htmlspecialchars($journey['category']); ?></td>
          <td class="journey-table__cell"><a href="journeys?action=read&id=<?= $journey['id'] ?>" class="btn btn-primary">Lire</a></td>
          <td class="journey-table__cell">
            <a href="uploadPicture?action=create&id=<?= $journey['id'] ?>" class="btn btn-primary" >Ajouter une photo</a>
          </td>
          <td class="journey-table__cell">
            <a href="journeys?action=delete&id=<?= $journey['id'] ?>" class="btn btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce voyage ?');">Effacer</a>
          </td>






          </td>
          </td>
          
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>