<h1>Mentions légales et conditions générales d'utilisation</h1>
<h3>Préambule :</h3>
<p>Easy voyage est une agence de voyage et un tour opérateur français qui propose via son site internet
    https://www.easyvoyage.com (ci–après, le « Site »), l'élaboration et la vente de voyages sur mesure à
    destination du monde entier.
    Les présentes Conditions Générales d'Utilisation (ci-après désignées « CGU ») ont vocation à s'appliquer de
    façon exclusive entre Easy Voyage et toute personne souhaitant accéder au Site et /ou utiliser les
    services proposés depuis le Site (ci-après, l'« Utilisateur »).</p>

<p>Toute utilisation des services proposés via le Site emporte de plein droit l'application des présentes CGU.
    Nous vous invitons à les lire attentivement.</p>

<p>Nous vous informons que les dispositions des présentes CGU sont susceptibles d'être modifiées notamment en
    raison de l'évolution législative et/ou réglementaire, sans que la responsabilité de Easy Voyage
    puisse être recherchée. Les modifications prendront effet à leur publication sur le Site (sauf indication
    contraire). La dernière version mise à jour, sera disponible à tous et accessible en permanence sur le Site,
    en cliquant sur le lien « Notice Légale & CGU » figurant en bas de page dans la rubrique "Autour du voyage".
</p>


<h3>Article 1 : Mentions légales</h3>

<p><b>1.1.</b>Le Site est édité par la société Easy Voyage, Société Anonyme au capital de 3.778.617
    euros, immatriculée au RCS de Paris sous le numéro 315 459 016, dont le siège social est situé au 55 rue
    Sainte Anne à Paris (75002), et représentée par Monsieur Alain Capestan.</p>

<p><b>1.2.</b> Le Site est hébergé par la société Claranet Artful, Société Anonyme au capital social de
    2.760.019 euros, immatriculée au RCS de Rennes sous le numéro B 412 899 387 dont le siège social est 5
    avenue des peupliers 35510 Cession Sevigne. Téléphone : (0)2.99.12.57.57.</p>

<p><b>1.3.</b> Easy Voyage est immatriculée au registre des opérateurs de voyages et de séjours (Atout
    France 79/81 rue de Clichy, 75009 PARIS) sous le numéro : 075100084. Elle dispose d'une garantie financière
    auprès d'ATRADIUS Credit Insurance N.V (44, avenue Georges Pompidou 92596 Levallois – Perret Cedex) et d'une
    Assurance Responsabilité Civile et Professionnelle : MMA – 14, boulevard Marie et Alexandre Oyon 72030 Le
    Mans Cedex 9 - Contrat n°146 161 560.
    N° ORIAS 18007991 - www.orias.fr<br></p>


<h3>Article 2 : Définition</h3>

<p>Site : désigne le site internet de la société Easy Voyage accessible depuis l'adresse
    https://www.voyageursdumonde.fr <br>

    <b>Utilisateur :</b> tout internaute qui navigue et/ou utilise les services proposés par Easy Voyage
    depuis le Site.<br>

    <b>Services :</b> désignent tous les services proposés par Easy Voyage à savoir les prestations de
    voyages ainsi que les prestations de services associés.<br>

    <b>Prospect :</b> tout internaute qui navigue sur le Site.<br>

    <b>Client :</b> tout internaute qui après avoir accédé au Site, (i) s'inscrit à la Newsletter, et/ou (ii)
    formule une demande de devis, et/ou (iii) accepte une proposition de prestations de voyage reçue de
    Easy Voyage.
</p>


<h3>Article 3 : Utilisation du Site</h3>

<p>Le Site est accessible gratuitement en tout lieu par tout Utilisateur disposant d'un accès à internet. Tous
    les frais supportés par l'Utilisateur pour accéder aux Services demeurent à sa charge. De même, Voyageurs du
    Monde ne saurait être tenue pour responsable de tout problème de connexion internet imputable à tout
    équipement et/ ou opérateur auxquels a recours l'Utilisateur (débit réduit ou connexion interrompue
    notamment).</p>

<p>Depuis le Site, les Utilisateurs ont accès aux informations et/ou aux Services suivants :

    • Une offre de voyage variée et portant sur la plupart des pays ouverts aux voyages (accès gratuit à tout
    internaute)<br>
    • Une information détaillée sur les divers produits et services proposés par Easy Voyage (accès
    gratuit à tout internaute)<br>
    • Un accès spécifique pour faire une demande de devis en ligne depuis la rubrique " Faites créer votre
    voyage "<br>
    • Un accès à un espace personnalisé accessible à tout Client disposant de codes d'accès pour visualiser le
    devis proposé par Easy Voyage et /ou le contrat de voyage souscrit.<br></p>


<h3>Article 4 : Garantie et Responsabilité</h3>

<p>Easy Voyage fera ses meilleurs efforts pour permettre l'accès au Site 24h/24, 7jours /7, sauf en cas
    de force majeure ou d'un événement hors de contrôle de Easy Voyage et sous réserve des éventuelles
    pannes et interventions de maintenance nécessaires au bon fonctionnement du Site.</p>

<p>En effet, pour la bonne gestion du Site, Easy Voyage pourra à tout moment :<br>

    • Suspendre, interrompre ou limiter l'accès à tout ou partie du Site, réserver l'accès au Site, ou à
    certaines parties du Site<br>
    • Supprimer toute information pouvant en perturber le fonctionnement ou entrant en contradiction avec la
    réglementation applicable<br>
    • Suspendre le Site afin de procéder à des mises à jour.</p>


<p>La responsabilité de Easy Voyage ne pourra être engagée en cas de défaillance, panne, difficulté ou
    interruption de fonctionnement, empêchant l'accès au Site ou à une de ses fonctionnalités.</p>

<p>Le matériel de connexion au Site demeure sous la responsabilité de l'Utilisateur qui devra prendre toutes les
    mesures appropriées pour protéger son matériel ainsi que ses propres données notamment en cas d'attaques
    virales par internet. La responsabilité de Easy Voyage ne pourra être recherchée, l'Utilisateur
    demeurant le seul responsable des sites internet et données consultés.</p>


<h3>Article 5 : Obligations générales de l'Utilisateur du Site</h3>

<p>L'Utilisateur s'engage à utiliser le Site conformément aux dispositions des présentes CGU, à l'ordre public
    et aux bonnes mœurs, dans le respect du droit de propriété intellectuelle et du droit à l'image. A défaut de
    respecter ces dispositions, Easy Voyage pourra engager la responsabilité de l'Utilisateur.</p>

<p>Vous devez conserver en toute sécurité tout identifiant et tout mot de passe vous permettant d'accéder au
    Site ou toute partie de ceux-ci comme étant strictement confidentiels, et vous ne devez permettre à aucune
    personne d'accéder à cet identifiant et à ce mot de passe et de les utiliser.
    Vous êtes responsable de toute activité en rapport avec les Services utilisés ou auxquels vous avez accédés
    via votre espace client. Vous devez immédiatement notifier Easy Voyage de toute utilisation non
    autorisée de vos identifiants et mot de passe en adressant un courriel à l'adresse suivante :
    EquipeRelationClients[@]voyageursdumonde.fr</p>

<p>En utilisant les Services, vous déclarez et garantissez que (a) toutes les informations que vous communiquez
    sont véridiques et précises ; (b) vous maintiendrez l'exactitude de ces informations ; (c) votre utilisation
    des Services ne viole aucune loi ou réglementation applicable.</p>


<h3>Article 6 : Propriété intellectuelle</h3>

<p>Tous contenus et matériels affichés sur le Site, tels que les textes, graphiques, vidéos, œuvres
    audiovisuelles, logos, photographies, icônes, images, clips audio et logiciels, sont la propriété de
    Easy Voyage ou de ses concédants de licence. Ces contenus et matériels sont protégés par les lois sur
    les droits d'auteur en vigueur en France et les lois internationales applicables.
    Les contenus et matériels présents sur le Site, exploités, concédés sous licence ou contrôlés par Voyageurs
    du Monde ne peuvent être copiés, sauf par un Utilisateur uniquement pour son utilisation personnelle. La
    modification ou l'utilisation du contenu ou matériel à toute autre fin violerait les droits de propriété
    intellectuelle de Easy Voyage et/ou de ses concédants de licence.
    De tels contenus et matériels ne peuvent être distribués, republiés, téléchargés ou transmis d'une
    quelconque manière, sans l'autorisation écrite préalable de Easy Voyage.</p>

<p>Easy Voyage, et autres marques et logos de Easy Voyage, déposés ou non (ci-après, les « Marques
    Easy Voyage »), sont la propriété de Easy Voyage. Toutes les autres marques sur le Service
    sont la propriété des détenteurs de marque respectifs (les « Marques de Tiers », et collectivement avec les
    Marques Easy Voyage, les « Marques »). L'utilisation non autorisée de ces Marques est interdite par
    la loi. Aucune partie du Service ni des CGU ne doit être interprétée comme concédant, implicitement, ou
    autrement, un(e) quelconque licence ou droit d'utilisation d'une quelconque Marque affichée sur ce Service
    sans une autorisation écrite préalable de Easy Voyage spécifique pour chaque utilisation.
    L'utilisation de toute Marque dans le cadre d'un lien vers ou depuis un quelconque site internet est
    interdite sans l'autorisation écrite préalable de Easy Voyage.</p>


<h3>Article 7 : Collecte des données personnelles</h3>

<p>Pour en savoir plus sur la collecte et le traitement des données à caractère personnel vous concernant ainsi
    que sur notre utilisation des Cookies, nous vous remercions de vous reporter à notre Politique en matière de
    Confidentialité et de Cookies : https://www.voyageursdumonde.fr/voyage-sur-mesure/divers/cookies.</p>


<h3>Article 8 : Loi applicable et Tribunal compétent</h3>

<p>Les présentes CGU sont soumises au droit français. Tout litige relatif à leur interprétation et /ou à leur
    exécution relève des tribunaux français.</p>


<h3>Article 9 : Contactez-nous</h3>

<p>Si vous souhaitez nous contacter, y compris si vous avez une quelconque réclamation, vous pouvez adresser un
    courrier à notre service Relations Clients à l'adresse suivante : Easy Voyage – Service Relations
    Clients, 55 rue Sainte-Anne 75002 Paris.</p>