<!-- <p id="message"></p> -->

<h1 class="titlePage">Se connecter</h1>

<form id="loginForm" action="" method="post">
    <label for="email">Email:</label>
    <input type="email" name="email" id="email" required>
    <br>
    <label for="password">Mot de passe:</label>
    <input type="password" name="password" id="password" required>
    <br>
    <button type="submit">Se connecter</button>
</form>


<script src="public/js/login.js"></script>