<h1>Politique en matière de Confidentialité et de Cookies</h1>
<p><b>Dernière mise à jour : 2 mai 2018
                Préambule</b></p>

<p>Easy Voyage, société anonyme immatriculée au registre du commerce et des sociétés de Paris sous le numéro
        315 459 016 et dont le siège social est situé au 55 rue Sainte-Anne 75002 Paris, tour-opérateur et agence de
        voyage français spécialisé dans la conception de voyages sur mesure à destination de la plupart des pays du
        monde, souhaite vous informer des mesures mises en œuvre en vue de protéger vos données personnelles et votre
        vie privée conformément à la législation en vigueur et plus particulièrement aux dispositions de la loi du 6
        janvier 1978 dite « Informatique et Libertés » modifiée, du Règlement européen 2016/679 ainsi que des
        recommandations émanant de la CNIL (ci-après « la Législation en vigueur »).</p>

<p>En application de la Législation en vigueur vous disposez d'un droit d'accès, d'opposition, de rectification, de
        suppression et de limitation des traitements sur les données personnelles vous concernant. Vous disposez
        également d'un droit de définir des directives relatives au sort de vos données personnelles après votre décès.
        Ces droits peuvent s'exercer par courrier postal à l'adresse suivante : Service Relations Clients, 55 rue
        Sainte-Anne, 75002 Paris en joignant à votre demande une copie de votre pièce d'identité (qui ne sera pas
        conservée par Easy Voyage et pourra soit être détruite, soit vous être restituée à votre convenance).
        Pour des raisons de sécurité, votre droit à la portabilité de vos données personnelles ne pourra être exercé que
        dans nos locaux en votre présence et sur présentation d'un justificatif d'identité en cours de validité. Vous
        disposez du droit d'introduire une réclamation auprès de la CNIL si vous considérez que nous ne respectons pas
        les règlementations applicables en matière de données personnelles.</p>

<p>En tant que responsable du traitement de vos données personnelles, Easy Voyage souhaite répondre à vos
        préoccupations relatives à la confidentialité des informations que vous nous transmettez par tous modes de
        communication notamment : site(s) internet édités et exploités par Easy Voyage, chat, communications
        téléphoniques, rendez-vous en agence avec nos conseillers (ci-après « les Canaux de Communication ») en vue de
        vous proposer nos produits et services.</p>

<p>Nous pouvons obtenir des informations à votre sujet auprès d'autres sources. Par exemple, nous pouvons
        solliciter un fournisseur ou collecteur tiers pour nous fournir des informations supplémentaires sur nos clients
        existants (l'ajout de données ou «data appending»), notamment des informations à partir de votre profil ou de
        vos publications sur un réseau social tiers.</p>

<p>Nous pouvons également collecter des informations figurant sur votre profil d'un réseau social tiers (notamment
        Facebook) si vous autorisez le réseau social tiers à nous les communiquer ou que vous les mettez en ligne
        publiquement. Ces informations peuvent être les informations générales relatives à votre compte (par exemple,
        nom, adresse électronique, photo de profil, sexe, date de naissance, ville actuelle, identifiant, liste d'amis,
        etc.) et toute autre information ou activité que vous autorisez le réseau social tiers à partager avec nous ou
        que vous mettez en ligne publiquement sur votre profil. Nous pouvons par exemple recevoir vos informations
        relatives aux réseaux sociaux (ou une partie de celles-ci) lorsque vous téléchargez ou interagissez avec l'une
        de nos applications sur un site de réseau social (notamment Facebook). Pour en savoir plus sur la manière dont
        vos informations relatives aux réseaux sociaux peuvent être obtenues par nous, veuillez consulter les conditions
        d'utilisation du réseau social tiers concerné.</p>

<p>Lorsque vous nous communiquez vos données personnelles, vous nous autorisez à les utiliser, à les analyser, à
        les conserver et, le cas échéant, à les transmettre à nos partenaires lorsque le traitement de vos demandes le
        nécessite. En nous communiquant des données personnelles via les Canaux de Communication, vous acceptez cette
        politique. Notre politique est susceptible d'être modifiée afin de tenir compte des évolutions de la Législation
        en vigueur en matière de données personnelles. Nous vous tiendrons informés de tout changement effectué.</p>




<h3>I. Données personnelles transmises à Easy Voyage.</h3>

<h4>a) Données relatives à vos informations personnelles</h4>
<p>Il s'agit d'informations vous concernant en tant que personne physique ou morale que vous avez volontairement
        communiquées à Easy Voyage via les différents Canaux de Communication et qui sont indispensables à la
        conception et à la réalisation de votre voyage (telles que notamment vos nom, prénom, adresse électronique,
        numéro de téléphone, adresse postale, date de naissance...).</p>

<p>Nous vous informons que les informations qui doivent être obligatoirement fournies à Easy Voyage sont
        signalées de manière visible par un astérisque sur notre site internet (ci-après, « le Site »). Les informations
        non signalées par un astérisque sont facultatives. Pour tout contact de votre part, par téléphone ou en agence,
        votre conseiller vous indique les informations indispensables dont il a besoin.</p>

<p>Ces informations sont indispensables au traitement de vos demandes de prestations de voyage, celles-ci ne
        pourront malheureusement pas être traitées en l'absence de ces informations.</p>



<h4>b) Données relatives aux informations personnelles de tiers</h4>
<p>Dans le cadre de votre demande de devis et par la suite de votre inscription, vous avez la possibilité de
        renseigner les coordonnées d'une ou plusieurs autres personnes (autres participants au voyage ou personnes ayant
        participé à une liste cadeau ou pour d'autres événements (union, anniversaire….), personne à prévenir en cas
        d'urgence …).</p>

<p>Dans ce cas de figure, les données des autres personnes renseignées ne seront utilisées par Easy Voyage
        qu'en vue d'assurer le traitement d'une demande de devis et par la suite d'une inscription. Si Voyageurs du
        Monde souhaite utiliser les données des autres personnes renseignées pour une autre finalité que celles
        précitées, Easy Voyage sollicitera au préalable leur consentement.</p>

<p>Dès lors, vous garantissez à Easy Voyage que les autres personnes dont vous communiquez les données sont
        informées de cette transmission les concernant et l'accepte.</p>

<p>Easy Voyage informera les personnes dont elle a collecté les données personnelles de manière indirecte,
        de leurs droits au titre de la présente politique, lors de sa première communication aux autres personnes
        renseignées par email et comprenant toutes les informations utiles à l'organisation de leur voyage.</p>



<h4>c) Mineurs</h4>
<p>Les différents Canaux de Communication ne sont, en principe, pas destinés à un usage par des mineurs sans
        autorisation de leurs parents ou responsable légal. Un mineur d'au moins 16 ans peut solliciter un devis en vue
        de l'organisation d'un voyage et fournir les données personnelles nécessaires à cette finalité. Voyageurs du
        Monde s'efforcera de vérifier compte tenu des informations renseignées et des moyens technologiques disponibles
        l'âge du mineur. En aucun cas, le mineur ne pourra finaliser, valider et payer le voyage sans le consentement du
        titulaire de l'autorité parentale.</p>

<p>Easy Voyage s'efforce raisonnablement de vérifier que le consentement est donné ou autorisé par le
        titulaire de l'autorité parentale à l'égard du mineur, compte tenu des moyens technologiques disponibles.</p>



<h4>d) Données sensibles</h4>
<p>Easy Voyage est amené à collecter des données de catégorie particulière telles que des données de santé
        (handicap, allergie ou conditions particulières) et de manière indirecte de connaître la religion, les croyances
        ou les convictions personnelles des personnes concernées bien que cette collecte ne soit jamais directe et ne se
        fasse que par déduction (cas du régime alimentaire). Ces données sont uniquement collectées pour les besoins de
        l'organisation du transport et/ou du voyage de la personne concernée et ne seront utilisées d'aucune autre
        manière.</p>




<h3>II. Données relatives à votre navigation sur le Site (cookies)</h3>
<p>Lors de vos navigations sur le site internet de Easy Voyage des cookies temporaires peuvent être
        enregistrés sur votre ordinateur.</p>


<h4>a) Qu'est-ce qu'un cookie ?</h4>
<p>Un « cookie », ou traceur, est un fichier texte qui permet à Easy Voyage d'identifier l'appareil dans
        lequel il est enregistré pendant la durée de validité ou d'enregistrement du cookie.</p>

<p>Au cours de votre navigation sur le Site, Easy Voyage peut enregistrer, dans un espace dédié du disque
        dur de votre appareil (ordinateur, tablette ou smartphone), un ou plusieurs « cookie » par l'intermédiaire du
        navigateur internet que vous utilisez et en fonction des paramètres que vous avez sélectionnés sur celui-ci en
        matière de cookies.</p>

<p>Ces informations sont notamment :<br>

        Le type de navigateur internet que vous utilisez ;<br>
        Le type de système et dispositif d'exploitation que vous utilisez pour accéder au service ;<br>
        Le nom de domaine de votre fournisseur de services internet ;<br>
        La page internet dont vous provenez ;<br>
        Le pays de résidence et votre langue ;<br>
        Les pages et options que vous visitez et auxquelles vous accédez sur nos Sites.</p>>
<p>Lors de votre première visite sur notre Site, dès lors que Easy Voyage envisagera de placer un cookie sur
        votre appareil, une bannière d'information s'affichera en bas de page. En poursuivant votre navigation sur le
        Site après avoir cliqué sur « J'accepte », vous consentez expressément à ce que Easy Voyage puisse
        déposer des cookies sur votre appareil (les cookies liés aux opérations relatives à la publicité ciblée,
        certains cookies de mesure d'audience, les cookies des réseaux sociaux générés notamment par leurs boutons de
        partage lorsqu'ils collectent des données personnelles). Si vous poursuivez votre navigation sur le site, des
        cookies pourront être déposés sur votre poste. Le bandeau restera affiché tant que vous n'aurez pas poursuivi la
        navigation, c'est-à-dire tant que vous ne vous serez pas rendu sur une autre page du Site ou que vous n'aurez
        pas cliqué sur un élément du Site. Si vous ne souhaitez pas accepter tout ou partie des cookies, nous vous
        recommandons de cliquer sur le lien « En savoir plus » sur le bandeau, et de suivre les instructions détaillées
        vous permettant de gérez les cookies via le paramétrage de votre navigateur.</p>

<p>Les cookies ne génèrent ni ne transmettent de virus informatiques susceptibles d'infecter votre appareil, ils ne
        sont lisibles et reconnaissables que par leur émetteur.</p>

<p>Vous avez la possibilité de modifier à tout moment les paramètres relatifs aux cookies. Vous trouverez ci-après
        des informations concernant les cookies et les différentes manières de gérer les paramètres liés aux cookies sur
        votre navigateur.</p>

<p>Le délai de validité du consentement au dépôt des Cookies est de 13 mois. À l'expiration de ce délai, nous
        solliciterons de nouveau votre consentement.</p>

<p>Si vous souhaitez en savoir plus sur les cookies et leur utilisation, vous pouvez consulter le dossier de la
        Commission Nationale de l'Informatique et des Libertés à l'adresse suivante : www.cnil.fr, rubrique « Cookies :
        les outils pour les maitriser ».</p>



<h4>b) Les cookies sur le Site</h4>
<p>Easy Voyage peut être amenée à utiliser les types de cookies suivants (bannière en bas de page) :<br>

        Cookies de gestion de session<br>
        Cookies de mesure d'audience (cookies statistiques)<br>
        Cookies nécessaires à certaines fonctionnalités optionnelles<br>
        Cookies relatifs à la publicité ciblée<br>
        Cookies des réseaux sociaux générés notamment par leurs boutons de partage lorsqu'ils collectent des données
        personnelles<br>
        Les cookies de gestion de session sont indispensables au bon fonctionnement du Site. Les refuser pourra
        entrainer un ralentissement et /ou un dysfonctionnement du Site.</p>

<p>Par l'analyse de la manière dont vous utilisez le Site, Easy Voyage peut vous proposer une meilleure
        navigation à l'effet de répondre de manière appropriée à vos attentes et également identifier les éventuels
        problèmes que vous rencontrez afin d'y apporter des solutions rapides.</p>

<p>Easy Voyage est susceptible d'intégrer sur son Site des applications informatiques de tiers vous
        permettant de partager des contenus du Site avec d'autres personnes. C'est notamment le cas du bouton « Partager
        » ou « J'aime » sur Facebook, Pinterest, Twitter, Instagram, YouTube ou encore LinkedIn. Le réseau social
        concerné est alors susceptible de vous identifier et d'enregistrer des cookies sur vos appareils. Nous vous
        invitons à consulter leur politique de confidentialité.</p>

<p>Vous avez la possibilité de vous opposer simplement aux cookies via les procédures détaillées au c) ci-dessous.</p>



<h4>c) Vos choix concernant les cookies</h4>
<p>Vous avez la possibilité de modifier à tout moment les paramètres de votre navigateur internet afin d'accepter,
        paramétrer ou, au contraire, refuser les cookies. Plusieurs options s'offrent à vous : accepter tous les
        cookies, être averti lorsqu'un cookie est enregistré, ou refuser systématiquement tous les cookies.</p>

<p>Easy Voyage vous informe que la désactivation des cookies de sessions ou de fonctionnalités peut avoir
        pour effet d'empêcher la consultation du Site. A ce titre, Easy Voyage ne saurait être tenue pour
        responsable en cas de fonctionnement dégradé de nos services lié aux paramétrages que vous aurez choisi.</p>

<p>Chaque navigateur internet propose des modalités de configuration différentes pour gérer les cookies. De manière
        générale, elles sont décrites dans le menu d'aide de chaque navigateur. Si vous utilisez un type ou une version
        de navigateur différent de ceux figurant sur la liste ci-dessous, nous vous invitons à consulter le menu « Aide
        » de votre navigateur.</p>

Vous utilisez Safari 5.0 (sur ordinateur) :<br>

<p>1. Choisissez Safari > Préférences puis cliquez sur « Sécurité » ;<br>
        2. Dans la section « Accepter les cookies », indiquez si et quand Safari doit accepter les cookies de sites web
        ;<br> Pour obtenir une explication sur les options qui vous sont proposées, cliquez sur le bouton aide « ? ».<br> Si
        vous avez paramétré le blocage systématique des cookies sur Safari, vous devrez peut-être accepter
        temporairement les cookies pour ouvrir une page. Répétez les étapes ci-dessus, en sélectionnant « Toujours ».
        Lorsque vous en avez terminé avec la page concernée, désactivez de nouveau les cookies et supprimez les cookies
        de la page.</p>

<p>Pour obtenir davantage d'informations, vous pouvez consulter la page suivante :
        http://support.apple.com/kb/ht1677?viewlocale=fr_FR</p>

<p>Vous utilisez Safari sur iOS (tablettes et smartphones) :<br>

        1. Ouvrir l'application « Réglages » et choisir « Safari » ;<br>
        2. Dans la rubrique « Confidentialité » allez à « Accepter les cookies » ;<br>
        3. Définissez vos paramètres de confidentialité.<br>

        Pour obtenir davantage d'informations, vous pouvez consulter la page suivante :
        http://support.apple.com/kb/ht1677?viewlocale=fr_FR</p>

<p>Vous utilisez Google Chrome :<br>

        1. Choisissez le menu « Paramètres » ;<br>
        2. Cliquez sur « Afficher les paramètres avancés » et aller au paragraphe « Confidentialité » ;<br>
        3. Cliquez sur « Paramètres du contenu » ;<br>
        4. Sélectionnez « Bloquer les cookies et données de sites tiers » pour bloquer les cookies.<br>

        Pour obtenir davantage d'informations, vous pouvez consulter la page suivante :
        https://support.google.com/chrome/answer/95647?hl=fr</p>

<p>Vous utilisez Mozilla Firefox :<br>

        1. Cliquez sur « Menu » puis « Options » ;<br>
        2. Sélectionnez l'icône « Vie privée » ;<br>
        3. Dans la zone Historique, pour l'option « Règles de conservation », sélectionnez « utiliser les paramètres
        personnalisés pour l'historique » ;<br>
        4. Cochez la case « Accepter les cookies » pour activer les cookies, ou décochez-la pour les désactiver. Si vous
        rencontrez des difficultés avec les cookies, assurez-vous que l'option « Accepter les cookies tiers » ne soit
        pas positionnée sur « Jamais ».<br>
        5. Choisissez la durée de conservation des cookies en sélectionnant au choix entre les 3 options (a), (b) ou (c)
        ci-dessous :<br>
        <b>(a) « leur expiration » :</b><br> Chaque cookie sera supprimé à sa date d'expiration, date fixée par le site émetteur du
        cookie.<br>
        <b>(b) « la fermeture de Firefox » :</b><br> les cookies enregistrés sur votre ordinateur seront supprimés lorsque vous
        fermerez la fenêtre de navigation Firefox.<br>
        <b>(c) « Me demander à chaque fois » :</b><br> un avertissement s'affichera chaque fois qu'un site web souhaite enregistrer
        un cookie, vous demandant si vous acceptez cet enregistrement ou non.<br>
        6. Cliquez sur OK pour fermer la fenêtre « Options » et valider vos choix.

        Pour obtenir davantage d'informations, vous pouvez consulter la page suivante :
        https://support.mozilla.org/fr/products/firefox/privacy-and-security/cookies
</p>

<p>Vous utilisez Internet Explorer 8.0 et plus :<br>

        1. Allez dans le menu « Outils », puis sélectionnez « Option Internet » ;<br>
        2. Cliquez sur l'onglet « Confidentialité » ;<br>
        3. Sélectionnez le niveau de confidentialité souhaité à l'aide du curseur : vers le haut jusqu'à « Bloquer tous
        les cookies » pour bloquer tous les cookies, ou vers le bas jusqu'à « Accepter tous les cookies » pour accepter
        tous les cookies.<br>

        Pour obtenir davantage d'informations, vous pouvez consulter la page suivante :
        http://windows.microsoft.com/fr-fr/internet-explorer/delete-manage-cookies</p>

<p>Vous utilisez Opéra :<br>

        1. Allez dans le menu « Fichier » puis sélectionnez « Préférences » ;<br>
        2. Cliquez sur l'icône « Vie privée » ;<br>
        3. Définissez les paramètres de confidentialité que vous souhaitez appliquer.<br></p>

<p>Vous utilisez Androïd :<br>

        1. Tapez sur la touche en haut à droite ;<br>
        2. Sélectionnez « Réglages » puis « Confidentialité et sécurité » ;<br>
        3. Définissez les paramètres de confidentialité que vous souhaitez appliquer.<br></p>

<p>Vous utilisez Dolphin sur Androïd :<br>

        1. Allez dans le menu et sélectionnez « Plus » puis « Réglages » ;<br>
        2. Sélectionnez « Confidentialité » puis « Sécurité » ;<br>
        3. Définissez les paramètres de confidentialité que vous souhaitez appliquer dans le menu « Cookies ».<br></p>




<h3>III. Pour quelles finalités vos données sont-elles recueillies ?</h3>

<h4>a) Répondre à vos demandes</h4>
<p>Lorsque vous entrez en contact avec Easy Voyage via les différents Canaux de Communication susmentionnés,
        la collecte de vos données personnelles peut avoir pour finalité :<br>

        - La fourniture d'un accès au Site et d'un accès à votre espace client dédié pour vous permettre, notamment, de
        consulter vos devis et/ou toute information relative à vos voyages ;<br>
        - L'exécution des demandes que vous avez effectuées sur le Site ou par les autres Canaux de Communication
        (réservation auprès de nos partenaires, établissement de votre contrat de vente, suivi de la réalisation des
        prestations de votre voyage, suivi de toutes demandes de votre part au titre de votre voyage y inclus après le
        retour de votre voyage, conformément aux délais de prescription légaux...) ;<br>
        - L'envoi de lettres d'informations (newsletters) et de toute autre documentation (brochures notamment) que vous
        avez sollicitées ;<br>
        - Répondre à vos questions ;<br>
        - Vous informer des nouveaux voyages ou services similaires susceptibles de vous intéresser ;<br>
        - Plus généralement, le respect des obligations légales, réglementaires, comptables et fiscales de Voyageurs du
        Monde ;<br>
        - Traiter les demandes et les plaintes formulées par ou sur vous-même en lien avec le voyage.</p>



<h4>b) Réaliser des statistiques</h4>
<p>Dans le cadre de l'amélioration de nos services, les données personnelles vous concernant collectées par
        Easy Voyage peuvent également avoir pour finalité :<br>

        - La réalisation de calculs statistiques concernant notamment la fréquentation du Site ;<br>
        - La réalisation d'enquêtes et de sondages ;<br>
        - La réalisation d'études et de recherches afin d'améliorer votre expérience avec Easy Voyage.</p>



<h4>c) Vous solliciter à l'occasion d'opérations marketing</h4>
<p>Vos données pourront également être utilisées à des fins commerciales :<br>

        - Gestion de toute inscription et désinscription aux lettres d'informations (newsletters) à votre demande ;<br>
        - Communication d'informations relatives à Easy Voyage et ses partenaires : nouveautés, produits et
        services, prospection commerciale et offres personnalisées.</p>




<h3>IV. Comment et pendant quelle durée ?</h3>

<h4>a) Sécurisation de vos données</h4>
<p>En tant que responsable du traitement de vos données personnelles, Easy Voyage met en œuvre toutes les
        mesures techniques et organisationnelles nécessaires au respect de la protection de vos données personnelles :<br>
        contrôle d'accès, sauvegardes, traçabilité, sécurité des locaux, mesures de protection et veille à limiter la
        quantité de données traitée eu égard aux finalités poursuivies.</p>



<h4>b) Durée de conservation de vos données</h4>
<p>Nous stockons ces informations pour une durée proportionnée, nécessaire à l'objectif pour lequel nous les
        traitons et en tout état de cause pour la durée nécessaire pour répondre à une obligation légale ou
        réglementaire. Les données sont conservées pendant une durée qui n'excède pas la durée nécessaire aux finalités
        suivantes :<br>

        > Newsletter : vos données seront conservées aussi longtemps que votre abonnement sera actif. Vous pouvez y
        mettre fin à tout moment et vous désabonner en cliquant sur le lien qui vous sera indiqué.<br>
        > Demande de devis de prestations de voyage, inscription et réalisation des prestations de voyage : les données
        nécessaires au traitement de votre demande seront conservées pendant la durée nécessaire à l'établissement d'un
        devis ou d'un contrat puis pendant la durée de votre voyage conformément à la législation applicable et en tout
        état de cause pour la durée nécessaire pour répondre à une obligation légale ou réglementaire.<br>
        > Offres commerciales : vos données seront conservées aussi longtemps que vous accepterez de recevoir nos offres
        commerciales. Vous pouvez les refuser à tout moment et vous désabonner en cliquant sur le lien qui vous sera
        indiqué.<br>
        > Statistiques et sondages : vos données seront conservées pendant la durée nécessaire à l'établissement de
        statistiques fiables et au traitement des sondages réalisés auprès de vous, avec votre accord.</p>




<h3>V. Pour quels destinataires ?</h3>

<h4>a) Easy Voyage et ses partenaires</h4>
<p>Nous tenons à vous informer qu'afin de permettre l'exécution des finalités mentionnées au point III ci-dessus,
        vos données pourront être stockées, traitées et transférées aux filiales et/ou partenaires de Voyageurs du
        Monde, notamment aux fournisseurs des prestations de services réservées (hôteliers, transporteurs…) ou aux
        prestataires techniques (informatique, hébergement, distribution d'emails, prestataire de paiement en ligne
        etc.), lesquels pourront être situés hors de l'Union Européenne.</p>

<p>Nos filiales et/ou partenaires s'engagent à n'utiliser vos données personnelles que pour exécuter certaines
        tâches indispensables à la réalisation des finalités mentionnées au point III ci-dessus, dans le strict respect
        de vos droits en matière de protection des données personnelles et conformément à la Législation en vigueur.</p>



<h4>b) Tiers non partenaires</h4>
<p>Easy Voyage s'engage à ne pas transférer ni vendre des données à caractère personnel vous concernant à
        des tiers non partenaires. Nous ne communiquons aucune donnée personnelle à des agences ou sociétés à des fins
        de marketing ou commerciales.</p>

<p>Si la loi, une autorité (par exemple l'administration fiscale ou la CNIL) ou un juge devait contraindre
        Easy Voyage à communiquer des données à caractère personnel vous concernant, Easy Voyage s'engage,
        dans la mesure du possible, à vous en aviser (sauf si Easy Voyage n'est pas autorisée à le faire
        notamment compte tenu des obligations légales ou judiciaires qui pourraient lui incomber).</p>

<p>Enfin, il se peut que nous achetions ou fusionnons ou que nous soyons achetés par une autre société ou que nous
        cédions tout ou partie de nos actifs. Dans un tel cas, vos données personnelles pourront être communiquées à une
        autre société, mais cette communication sera soumise à la politique en matière de protection de la
        confidentialité et de cookies en vigueur.</p>




<h3>VI. Comment les liens se trouvant sur les Sites renvoyant vers d'autres sites m'affectent ?</h3>
<p>Nous pouvons à l'occasion placer des liens sur notre Site renvoyant vers d'autres sites internet et applications
        exploités par des tiers. Ces liens sont uniquement présents pour votre commodité et visent à apporter une valeur
        ajoutée à votre visite. Toutefois, en incluant ces liens, nous n'avons aucun contrôle sur ces sites internet et
        applications, lesquels sont indépendants de Easy Voyage et ont des politiques en matière de protection de
        la confidentialité distinctes. Lorsque vous quittez notre Site, sachez que nos politiques cessent de
        s'appliquer. Par conséquent, nous ne serons pas responsables de l'exactitude, de la pertinence, de la
        disponibilité, de la fiabilité, du respect des droits d'auteur, de la légalité ou de la décence du matériel
        contenu dans les sites internet et applications tiers liés à notre Site. Nous vous encourageons grandement à
        consulter les conditions et les politiques en matière de protection de la confidentialité de tout site internet
        et application tiers avant d'utiliser leurs sites.</p>




<h3>VII. Comment pouvez-vous accéder aux informations de « votre espace », les mettre à jour ou les supprimer ?</h3>
<p>Pour modifier une ou plusieurs données personnelles renseignées dans votre Espace Client, nous vous invitons à
        contacter votre conseiller et /ou à adresser votre demande à l'adresse mail suivante : dpd@voyageursdumonde.fr.</p>




<h3>VIII. Que faire si vous avez d'autres questions concernant la politique en matière de protection de la
        confidentialité et de cookies de Easy Voyage ?</h3>
<p>Si vous avez des questions ou des doutes quant à la présente politique en matière de protection de la
        confidentialité et de cookies, vous pouvez nous contacter, par email à l'adresse dpd@voyageursdumonde.fr ou en
        nous envoyant un courrier postal à Easy Voyage à l'attention du Délégué à la Protection des Données
        Personnelles - 55 rue Sainte Anne - 75002 Paris.</p>