<?php if ($journey && is_array($journey)) : ?>
    <div class="journey-details">
        <div class="journey-details__intro">
            <h1 class="journey-details__title"><?php echo $journey['journey_title']; ?></h1>
            <p class="journey-details__description"><?php echo $journey['journey_description']; ?></p>
        </div>
        <div class="slider journey-details__slider">
            <div class="slider__slides">
                <?php if (isset($journeys_pictures[$journey['id']])) : ?>
                    <?php foreach ($journeys_pictures[$journey['id']] as $index => $picture) : ?>
                        <img src="public/img/country/<?php echo $picture['picture']; ?>" <?php echo $index === 0 ? 'class="slider__slide slider__slide--active"' : 'class="slider__slide"'; ?>>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="slider__controls">
                <button class="slider__control slider__control--left">
                    <img src="public/img/svg/left.svg">
                </button>
                <button class="slider__control slider__control--right">
                    <img src="public/img/svg/right.svg">
                </button>
            </div>
            <div class="slider__circles">
                <?php if (isset($journeys_pictures[$journey['id']])) : ?>
                    <?php foreach ($journeys_pictures[$journey['id']] as $index => $picture) : ?>
                        <button data-clic="<?php echo $index + 1; ?>" class="slider__circle <?php echo $index === 0 ? 'slider__circle--active' : ''; ?>"></button>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="journey-details__hostel">
    <div class="journey-details__hostel-content">
        <h3 class="journey-details__hostel-title"><?php echo $journey['hostel_title']; ?></h3>
        <p class="journey-details__hostel-description"><?php echo $journey['hostel_description']; ?></p>
    </div>
    <p class="journey-details__hostel-image"><img src="public/img/hostel/<?php echo htmlspecialchars($journey['hostel_picture']); ?>" alt="Hôtel image"></p>
</div>
<div class="journey-details__circuit">
    <div class="journey-details__circuit-content">
        <h3 class="journey-details__circuit-title"><?php echo $journey['circuit_title']; ?></h3>
        <p class="journey-details__circuit-description"><?php echo $journey['circuit_description']; ?></p>
    </div>
    <p class="journey-details__circuit-image"><img src="public/img/circuit/<?php echo htmlspecialchars($journey['circuit_picture']); ?>" alt="Circuit image"></p>
</div>
        <p class="journey-details__formalities"><b>Formalités :</b> <?php echo $journey['formalities']; ?></p>
        <div class="journey-details__infos">
            <p class="journey-details__duration"><b>Durée du voyage :</b> <?php echo $journey['journey_duration']; ?></p>
            <p class="journey-details__price"><b>Prix :</b> <?php echo $journey['journey_price']; ?>€</p>
        </div>
    </div>
    
<?php else : ?>
    <p class="journey-details__no-results">Aucun voyage trouvé avec l'ID donné.</p>
<?php endif; ?>
<script src="public/js/slider.js"></script>