<div class="container">
    <h1>Message</h1>
    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>Auteur</th>
                <td><?= htmlspecialchars($message['firstname']) . " " . htmlspecialchars($message['lastname']) ?></td>
            </tr>
            <tr>
                <th>Email</th>
                <td><?= htmlspecialchars($message['email']) ?></td>
            </tr>
            <tr>
                <th>Date</th>
                <td><?= htmlspecialchars($message['date_creation']) ?></td>
            </tr>
            <tr>
                <th>Titre</th>
                <td><?= htmlspecialchars($message['title']) ?></td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td><?= nl2br(htmlspecialchars($message['content'])) ?></td>
            </tr>
            <tr>
    <th>Archiver</th>
    <td><a href="archiveMessage?id=<?= htmlspecialchars($message['id']) ?>" class="btn btn-warning" onclick="return confirm('Êtes-vous sûr de vouloir archiver ce message ?')">Archiver</a></td>
</tr>

            <tr>
    <th>Supprimer</th>
   
    <td><a href="deleteMessage?id=<?= htmlspecialchars($message['id']) ?>" class="btn btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce message ?')">Effacer</a></td>
</tr>

        </tbody>
    </table>
</div>
