<h1 class="titlePage">Inscription</h1>

<?php if (isset($_GET['error']) && $_GET['error'] === 'password_mismatch') : ?>
    <p>Les mots de passe ne correspondent pas.</p>
<?php endif; ?>
<form id="formRegister" action="" method="post" class="inscription-form">
    <label for="firstname">Prénom:</label>
    <input type="text" id="firstname" name="firstname">
    <br>
    <label for="lastname">Nom:</label>
    <input type="text" id="lastname" name="lastname">
    <br>
    <label for="email">Email:</label>
    <input type="email" id="email" name="email">
    <br>
    <label for="password">Mot de passe (8 caractères minimum, avec au moins un chiffre):</label>
    <input type="password" id="password" name="password" pattern="(?=.*\d).{8,}">
    <br>
    <label for="password_confirm">Confirmez le mot de passe:</label>
    <input type="password" id="password_confirm" name="password_confirm">
    <br>
    <input class="submit" type="submit" value="S'inscrire">
</form>
</div>

<!-- <p id="messageRegister"></p> -->
<script src="public/js/register.js"></script>