<div class="about-section">
  <h1>Contacter un agent</h1>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, aliquam.</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A, voluptatem provident quod dolorum quo nihil, fugiat nemo reiciendis similique et aliquid sequi nobis quidem vero velit odit ducimus fuga veniam ab voluptatibus sunt. Modi ipsum sed fuga error placeat iusto, doloribus dicta? Fuga accusamus dolorum fugit hic expedita itaque necessitatibus?</p>
</div>

<h2 style="text-align:center">Vos conseillers</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="public\img\aboutUs\pierre.jpg" alt="Jane" style="width:100%">
      <div class="container">
        <h2>Pierre</h2>
        <p class="title">Spécialiste de l'Asie</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe, quasi nisi. Dicta obcaecati dignissimos architecto nemo aspernatur temporibus magnam corrupti?</p>
        <p>pierre@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="public\img\aboutUs\sandra.jpg" alt="Mike" style="width:100%">
      <div class="container">
        <h2>Sandra</h2>
        <p class="title">Specialiste de l'Afrique et de l'Océanie</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe, quasi nisi. Dicta obcaecati dignissimos architecto nemo aspernatur temporibus magnam corrupti?</p>
        <p>sandra@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="public\img\aboutUs\florence.jpg" alt="John" style="width:100%">
      <div class="container">
        <h2>Florence</h2>
        <p class="title">Spécialiste de l'Europe et des USA</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe, quasi nisi. Dicta obcaecati dignissimos architecto nemo aspernatur temporibus magnam corrupti?</p>
        <p>florence@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>