<!-- <form action="uploadPicture" method="post" enctype="multipart/form-data"> -->
<form action="uploadPicture?id=<?= $journey['id'] ?>" method="post" enctype="multipart/form-data">

    <table>
    <thead>
      <tr class="journey-table__row">
        <th class="journey-table__header">ID</th>
        <th class="journey-table__header">Nom du séjour</th>
</tr>
</thead>
<tbody>
      
        <tr class="journey-table__row">
          <td class="journey-table__cell"><?= htmlspecialchars($journey['id']) ?></td>
          <td class="journey-table__cell"><?= htmlspecialchars($journey['journey_label']) ?></td>
        
        </tr>
    
   
    <tr>
            <td><label for="picture">Sélectionnez une image à télécharger:</label></td>
            <td><input type="file" name="picture" id="picture" required></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: center;">
                <input type="submit" value="Télécharger l'image" name="submit">
            </td>
        </tr>
        </tbody>
    </table>
</form>