<?php

$routes=[
    ''=>'home.php',
    'home' => 'home.php',
    'categoryJourneys' => 'categoryJourneys.php',
    'contact' => 'contact.php',
    'contactAjax' => 'contactAjax.php',
    'countryJourneys' => 'countryJourneys.php',
    'createJourney' => 'createJourney.php',
    'createJourneyAjax' => 'createJourneyAjax.php',
    'departureJourneys' => 'departureJourneys.php',
    'deleteMessage'=>'deleteMessage.php',
    'journeys' => 'journeys.php',
    'law' => 'law.php',
    'listUsers' => 'listUsers.php',
    'login' => 'login.php',
    'logout'=>'logout.php',
    'message' => 'message.php',
    'politics' => 'politics.php',
    'readJourney' => 'readJourney.php',
    'readJourneysCustomer' => 'readJourneysCustomer.php',
    'readMessage' => 'readMessage.php',
    'register' => 'register.php',
    'registerAjax' => 'registerAjax.php',
    'team' => 'team.php',
    'unauthorized' => 'unauthorized.php',
    'uploadPicture' => 'uploadPicture.php',
    'loginAjax' =>'loginAjax.php',
    'archiveMessage' =>'archiveMessage.php',
    ];
return $routes;